### ISSUE TITLE
Call to undefined function Askedio\LaravelRatchet\Providers\resource_path()

### ISSUE THREAD

**Issue by devfelipereis** [Askedio/laravel-ratchet#10]
> [Symfony\Component\Debug\Exception\FatalThrowableError]                      
>   Call to undefined function Askedio\LaravelRatchet\Providers\resource_path() 

I fixed with a helper function from laravel at Askedio\LaravelRatchet\Providers\LaravelRatchetServiceProvider. This is the function:

```
public function resource_path($path = '')
{
       return app()->basePath().'/resources'.($path ? '/'.$path : $path);
}
```

resource_path() helper function isn't available in laravel 5.1 which is the version I'm using. I don't know if anything else could fail and I'm going to test the rest right now.

What is the compatibility of this project with Laravel? Thank you!

**Comment by gcphost** [comment]
Hi

Project is made for 5.2-5.3.
