### ISSUE TITLE
ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by exzib** [Askedio/laravel-ratchet#12]
Hi.

I'm trying to connect to the websocket in javascript console but it returns ERR_CONNECTION_TIMED_OUT

I use the default settings from installation:
http://i.imgur.com/0rt30Pd.png

And it returns this:
http://i.imgur.com/XUT9KDk.png

This is a live server, i also have php artisan ratchet:serve running

**Comment by gcphost** [comment]
Did you start the service?

```
php artisan ratchet:serve
```

```
Starting WampServer server on: 0.0.0.0:8080
Starting ZMQ server on: 127.0.0.1:5555
```

I just updated my test package to Laravel 5.5, ran it, then (after npm install ws) I ran `node tests/index.js` from the package folder.
```
node index.js 
connected
[0,"117548739759a6f5470a7b2719558194",1,"Ratchet\/0.3.6"]
disconnected
```

```
onOpen (117548739759a6f5470a7b2719558194)
onClose (117548739759a6f5470a7b2719558194)
```

I'm using default settings.

If service is started the issue could be due to routing.
