### ISSUE TITLE
Ahh an installation problem

### ISSUE THREAD

**Issue by davs20** [Askedio/laravel-ratchet#13]
Problem 1
  - The requested package sidney/latchet-5-latchet could not be found in any v
sion, there may be a typo in the package name.
Problem 2
  - Installation request for askedio/laravel-ratchet ^0.6.0 -> satisfiable by
kedio/laravel-ratchet[0.6].
  - askedio/laravel-ratchet 0.6 requires ext-zmq * -> the requested PHP extens
n zmq is missing from your system.

tential causes:
 A typo in the package name
 The package is not available in a stable-enough version according to your min
um-stability setting
 see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more det
ls.

ad <https://getcomposer.org/doc/articles/troubleshooting.md> for further commo
problems.
To enable extensions, verify that they are enabled in your .ini files:
  - C:\xampp\php\php.ini
You can also run `php --ini` inside terminal to see which files are used by PH
in CLI mode.

stallation failed, reverting ./composer.json to its original content.

**Comment by gcphost** [comment]
I dont see anything in the deps for `sidney/latchet-5-latchet`.

This package requires `zmq`

```
the requested PHP extension zmq is missing from your system.
```

You will need to install it to PHP before you can install this package and its deps.
