### ISSUE TITLE
Throttling never backs off, too easy to hit connection attempt limit

### ISSUE THREAD

**Issue by francislavoie** [Askedio/laravel-ratchet#20]
It doesn't seem to be possible to configure the connection attempt limit.

During development where I refresh my pages a lot, I keep hitting the attempt limit. There doesn't seem to be anything to clean up the throttle over time. This makes the throttling essentially useless for me, I can't use it in production.

See #19, the functions that configure throttling are also private, so I can't modify them to my liking either without re-implementing them. Also, `onOpen` which calls those is public, but if I override that function, I'm stuck having to call `parent::onOpen` because it uses private functions, which again, isn't what I want to do. Making them protected instead lets me override them with my own logic without causing a mess.

**Comment by gcphost** [comment]
Thanks. I've merged your PR.

**Comment by francislavoie** [comment]
I'll just say #19 isn't _really_ a fix, but it allows people to add their own workarounds. There's still the issue that connection throttling never gets cleared, as far as I can tell... which is pretty useless because it means a user can only visit your site X number of times before the site breaks for them, unless the ratchet server is rebooted.
