### ISSUE TITLE
Not working with Lumen 5.5

### ISSUE THREAD

**Issue by puneetthakur66** [Askedio/laravel-ratchet#22]
I am trying to install the package showing below error.

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for askedio/laravel-ratchet ^1.1 -> satisfiable by askedio/laravel-ratchet[1.1].
    - Conclusion: remove evenement/evenement v3.0.1
    - Conclusion: don't install evenement/evenement v3.0.1
    - askedio/laravel-ratchet 1.1 requires react/zmq 0.2.*|0.3.* -> satisfiable by react/zmq[v0.2.0, v0.3.0].
    - react/zmq v0.2.0 requires evenement/evenement ~1.0 -> satisfiable by evenement/evenement[1.0.x-dev].
    - react/zmq v0.3.0 requires evenement/evenement ~2.0 -> satisfiable by evenement/evenement[2.0.x-dev, v2.0.0, v2.1.0].
    - Can only install one of: evenement/evenement[1.0.x-dev, v3.0.1].
    - Can only install one of: evenement/evenement[2.0.x-dev, v3.0.1].
    - Can only install one of: evenement/evenement[v2.0.0, v3.0.1].
    - Can only install one of: evenement/evenement[v2.1.0, v3.0.1].
    - Installation request for evenement/evenement (locked at v3.0.1, required as ^3.0 || ^2.0) -> satisfiable by evenement/evenement[v3.0.1].

Not able to figure out what's wrong in the installation.

**Comment by simonhamp** [comment]
@puneetthakur66 please can you share your `require` and `require-dev` from your project's `composer.json`?

**Comment by simonhamp** [comment]
@puneetthakur66 did you manage to make any progress on this?

**Comment by gcphost** [comment]
Hi @puneetthakur66, any follow up?
