### ISSUE TITLE
Issue with IpBlackList

### ISSUE THREAD

**Issue by rakib-09** [Askedio/laravel-ratchet#23]
I think here's a problem when I tried to intregate with lumen 5.5.

```
Type error: Argument 1 passed to Ratchet\Server\IpBlackList::__construct() must implement interface Ratchet\MessageComponentInterface, instance of Askedio\LaravelRatchet\PusherExample given, called in D:\practice\lumen\vendo
  r\askedio\laravel-ratchet\src\Console\Commands\RatchetServerCommand.php on line 85
```
**I solve this issue though.** 
I modified in **_IpBlackList.php_** file 
```
    public function __construct(MessageComponentInterface $component) {
        $this->_decorating = $component;
    }
```
**to:**
```
    public function __construct(PusherExample $component) {
        $this->_decorating = $component;
    }
```

**Comment by simonhamp** [comment]
IpBlacklist isn't a part of this package, it's from the Ratchet library. I wouldn't go changing that as it will break your ability to update to the latest version via Composer.

Which version of this package are you using?

**Comment by rakib-09** [comment]
I am using `askedio/laravel-ratchet` version 0.7.0

**Comment by simonhamp** [comment]
It seems that the `PusherExample` class that shipped with that version is not really suitable. I think it's also down to the ordering of how things are booted up in the console command.

Are you able to upgrade to at least `v1.0.0`?

**Comment by rakib-09** [comment]
Okay i am upgrading to v 1.0.0...
Thank you ...

**Comment by simonhamp** [comment]
@rakib-09 How did you get on? Did that solve your problem?

**Comment by gcphost** [comment]
Hi @rakib-09, any follow up?

**Comment by rakib-09** [comment]
@simonhamp  and @gcphost  sorry for my late reply. 
This is working nice with laravel 5.5.*.
but not working with 5.6.* :(

**Comment by simonhamp** [comment]
I haven't tested on 5.6 yet. What error are you getting?

**Comment by simonhamp** [comment]
@rakib-09 #26 got merged earlier... does this fix it for you?

**Comment by simonhamp** [comment]
@rakib-09 I'm closing this as there's been no response. If you have any other problems, please open a new issue.
