### ISSUE TITLE
keepAlive support

### ISSUE THREAD

**Issue by Navi2016** [Askedio/laravel-ratchet#5]
Hi,

It would be great if you could update this to the latest version soon and implement the keepAlive support (ping/pong).

See:
https://github.com/ratchetphp/Ratchet/blob/b0e72bb7da661fae9fbaa10895ab8bd556d1b508/src/Ratchet/WebSocket/WsServer.php#L200

Thanks!

**Comment by gcphost** [comment]
I agree this would be great but unfortunately I have a deadline at the end of the month so it will be a while before I can get to it. I thought I'd let you know instead of leaving this hanging.

**Comment by gcphost** [comment]
Updated composer to require ^0.3 so it should now be using the latest version.

Let me know if there are any issues.
