### ISSUE TITLE
Support for laravel 5.3

### ISSUE THREAD

**Issue by MilosR** [Askedio/laravel-ratchet#6]
Will it be available? 
Now it requires Laravel 5.2.*

**Comment by gcphost** [comment]
I can try it with 5.3 after work today.

**Comment by gcphost** [comment]
Sorry, maybe tomorrow :D

**Comment by MilosR** [comment]
Looks like it works fine with 5.3 (i have tried IoServer driver only).

However, artisan:publish is not working because of collect() helper. What have i done, i have replaced it with `[]`, array, and then in RatchetServerCommand, line 84 call collect helper and all() method. Tried it with telnet and it works.

Another note: Looks Like IoServer is not default driver, but in documentation stands that it is.

**Comment by gcphost** [comment]
Awesome! Thanks for trying, feel free to send any PRs.

I'm interested to see why `collect([])` wont work anymore in the config, that was a pretty nice feature.

**Comment by kikemarto** [comment]
Hello,

When it is operating in laravel 5.3? I'm waiting for inclusion in a project.

Greetings.

**Comment by gcphost** [comment]
Tested 5.3 with the default setup and it seems to work, will continue testing before pushing a release.

**Comment by gcphost** [comment]
Tested all 3 drivers (lightly) and it seems to work, collect gave me no issue on `php artisan vendor:publish`.

**Comment by gcphost** [comment]
I've posted the changes, feel free to give it a go.

https://github.com/Askedio/laravel-ratchet/releases/tag/0.6
